/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint for ECS/ALB.
         *
         *     Returns basic status without checking database to ensure fast response.
         *     For detailed health including database, use /health/detailed
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check Detailed
         * @description Detailed health check including database connectivity.
         *
         *     This endpoint checks:
         *     - Application status
         *     - Database connection
         *
         *     Returns 200 if all checks pass, 503 if any check fails.
         */
        get: operations["health_check_detailed_health_detailed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reviews
         * @description Retrieve reviews with optional filtering (no authentication required).
         *
         *     Query parameters:
         *         - professor_name: Get reviews for a specific professor
         *         - course_code + university: Get reviews for a specific course at a university
         *         - No filters: Get all reviews
         *
         *     Args:
         *         professor_name: Professor name to filter by
         *         course_code: Course code to filter by
         *         university: University to filter by
         *         skip: Number of records to skip
         *         limit: Maximum number of records to return
         *         review_storage: Review storage dependency
         *
         *     Returns:
         *         List of reviews
         */
        get: operations["list_reviews_api_v1_reviews__get"];
        put?: never;
        /**
         * Create Review
         * @description Create a new review (requires authentication).
         *
         *     Args:
         *         review_in: Review creation data
         *         review_storage: Review storage dependency
         *         course_storage: Course storage dependency
         *         university_storage: University storage dependency
         *         current_user: Current authenticated user
         *
         *     Returns:
         *         Created review
         */
        post: operations["create_review_api_v1_reviews__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Reviews
         * @description Get current user's reviews (requires authentication).
         *
         *     Args:
         *         skip: Number of records to skip
         *         limit: Maximum number of records to return
         *         review_storage: Review storage dependency
         *         current_user: Current authenticated user
         *
         *     Returns:
         *         List of user's reviews
         */
        get: operations["get_my_reviews_api_v1_reviews_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review Stats
         * @description Get aggregated review statistics.
         *
         *     Query parameters:
         *         - professor_name: Get stats for a specific professor
         *         - course_code + university: Get stats for a specific course at a university
         *
         *     Args:
         *         professor_name: Professor name to filter by
         *         course_code: Course code to filter by
         *         university: University to filter by
         *         review_storage: Review storage dependency
         *
         *     Returns:
         *         Dictionary with average ratings and review count
         */
        get: operations["get_review_stats_api_v1_reviews_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review
         * @description Get a specific review by ID.
         *
         *     Args:
         *         review_id: Review ID
         *         review_storage: Review storage dependency
         *
         *     Returns:
         *         Review
         *
         *     Raises:
         *         HTTPException: If review not found
         */
        get: operations["get_review_api_v1_reviews__review_id__get"];
        /**
         * Update Review
         * @description Update a review (requires authentication, only owner can update).
         *
         *     Args:
         *         review_id: Review ID
         *         review_in: Review update data
         *         review_storage: Review storage dependency
         *         current_user: Current authenticated user
         *
         *     Returns:
         *         Updated review
         *
         *     Raises:
         *         HTTPException: If review not found or user is not the owner
         */
        put: operations["update_review_api_v1_reviews__review_id__put"];
        post?: never;
        /**
         * Delete Review
         * @description Delete a review (requires authentication, only owner can delete).
         *
         *     Args:
         *         review_id: Review ID
         *         review_storage: Review storage dependency
         *         current_user: Current authenticated user
         *
         *     Raises:
         *         HTTPException: If review not found or user is not the owner
         */
        delete: operations["delete_review_api_v1_reviews__review_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Professors
         * @description List all professors with optional name filtering.
         *
         *     Returns professors extracted from reviews with their review counts.
         *
         *     Args:
         *         name: Filter by professor name (partial match)
         *         skip: Number of records to skip
         *         limit: Maximum number of records to return
         *         professor_storage: Professor storage dependency
         *
         *     Returns:
         *         List of professors with review counts
         */
        get: operations["list_professors_api_v1_professors__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professors/{professor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Professor
         * @description Get a specific professor by ID.
         *
         *     Args:
         *         professor_id: Professor ID
         *         professor_storage: Professor storage dependency
         *
         *     Returns:
         *         Professor details
         *
         *     Raises:
         *         HTTPException: If professor not found
         */
        get: operations["get_professor_api_v1_professors__professor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professors/{professor_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Professor Reviews
         * @description Get reviews for a specific professor.
         *
         *     Args:
         *         professor_id: Professor ID
         *         professor_storage: Professor storage dependency
         *         review_storage: Review storage dependency
         *         skip: Number of records to skip
         *         limit: Maximum number of records to return
         *
         *     Returns:
         *         List of reviews for the professor
         *
         *     Raises:
         *         HTTPException: If professor not found
         */
        get: operations["get_professor_reviews_api_v1_professors__professor_id__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professors/{professor_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Professor Stats
         * @description Get statistics for a specific professor.
         *
         *     Args:
         *         professor_id: Professor ID
         *         professor_storage: Professor storage dependency
         *         review_storage: Review storage dependency
         *
         *     Returns:
         *         Professor statistics including average ratings and review count
         *
         *     Raises:
         *         HTTPException: If professor not found
         */
        get: operations["get_professor_stats_api_v1_professors__professor_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Courses
         * @description List all courses with optional filtering.
         *
         *     Returns courses extracted from reviews with their review counts.
         *     A course is identified by the combination of course code and university.
         *
         *     Args:
         *         code: Filter by course code (partial match)
         *         university: Filter by university (exact match)
         *         skip: Number of records to skip
         *         limit: Maximum number of records to return
         *         course_storage: Course storage dependency
         *
         *     Returns:
         *         List of courses with review counts
         */
        get: operations["list_courses_api_v1_courses__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Course
         * @description Get a specific course by ID.
         *
         *     Args:
         *         course_id: Course ID
         *         course_storage: Course storage dependency
         *
         *     Returns:
         *         Course details
         *
         *     Raises:
         *         HTTPException: If course not found
         */
        get: operations["get_course_api_v1_courses__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Course Reviews
         * @description Get reviews for a specific course.
         *
         *     Args:
         *         course_id: Course ID
         *         course_storage: Course storage dependency
         *         review_storage: Review storage dependency
         *         skip: Number of records to skip
         *         limit: Maximum number of records to return
         *
         *     Returns:
         *         List of reviews for the course
         *
         *     Raises:
         *         HTTPException: If course not found
         */
        get: operations["get_course_reviews_api_v1_courses__course_id__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Course Stats
         * @description Get statistics for a specific course.
         *
         *     Args:
         *         course_id: Course ID
         *         course_storage: Course storage dependency
         *         review_storage: Review storage dependency
         *
         *     Returns:
         *         Course statistics including average ratings and review count
         *
         *     Raises:
         *         HTTPException: If course not found
         */
        get: operations["get_course_stats_api_v1_courses__course_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}/professors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Course Professors
         * @description Get professors who have taught this course.
         *
         *     Args:
         *         course_id: Course ID
         *         course_storage: Course storage dependency
         *         professor_storage: Professor storage dependency
         *         review_storage: Review storage dependency
         *
         *     Returns:
         *         List of professors who taught this course
         *
         *     Raises:
         *         HTTPException: If course not found
         */
        get: operations["get_course_professors_api_v1_courses__course_id__professors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/universities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Universities
         * @description List all universities with optional name filtering.
         *
         *     Returns universities extracted from reviews with their review counts.
         *
         *     Args:
         *         name: Filter by university name (partial match)
         *         skip: Number of records to skip
         *         limit: Maximum number of records to return
         *         university_storage: University storage dependency
         *
         *     Returns:
         *         List of universities with review counts
         */
        get: operations["list_universities_api_v1_universities__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/professors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Professors
         * @description Search professors by name (fuzzy search).
         *
         *     Supports partial name matching, case-insensitive.
         *
         *     Args:
         *         q: Search query for professor name
         *         professor_storage: Professor storage dependency
         *
         *     Returns:
         *         List of professor names that match the query
         */
        get: operations["search_professors_api_v1_search_professors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Courses
         * @description Search courses by code.
         *
         *     Supports both exact and partial matching, case-insensitive.
         *
         *     Args:
         *         q: Search query for course code
         *         exact: Whether to use exact match (default: true)
         *         course_storage: Course storage dependency
         *
         *     Returns:
         *         List of courses that match the query
         */
        get: operations["search_courses_api_v1_search_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/global": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global Search
         * @description Global search across professors and courses.
         *
         *     Searches both professors (fuzzy) and courses (exact match).
         *
         *     Args:
         *         q: Search query
         *         professor_storage: Professor storage dependency
         *         course_storage: Course storage dependency
         *
         *     Returns:
         *         Dictionary with professors and courses results
         */
        get: operations["global_search_api_v1_search_global_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Stats
         * @description Get search statistics.
         *
         *     Returns total counts of professors, courses, universities, and reviews.
         *
         *     Args:
         *         professor_storage: Professor storage dependency
         *         course_storage: Course storage dependency
         *         university_storage: University storage dependency
         *         review_storage: Review storage dependency
         *
         *     Returns:
         *         Dictionary with search statistics
         */
        get: operations["search_stats_api_v1_search_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Course
         * @description Course response schema.
         */
        Course: {
            /**
             * Code
             * @description Course code
             */
            code: string;
            /**
             * Name
             * @description Course name
             */
            name: string;
            /**
             * University Id
             * @description University ID offering this course
             */
            university_id: number;
            /**
             * Id
             * @description Course ID
             */
            id: number;
            /**
             * University
             * @description University name offering this course
             */
            university: string;
            /**
             * Review Count
             * @description Number of reviews for this course
             */
            review_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Professor
         * @description Professor response schema.
         */
        Professor: {
            /**
             * Name
             * @description Professor name
             */
            name: string;
            /**
             * University Id
             * @description University ID where professor teaches
             */
            university_id: number;
            /**
             * Id
             * @description Professor ID
             */
            id: number;
            /**
             * University
             * @description University name where professor teaches
             */
            university: string;
            /**
             * Review Count
             * @description Number of reviews for this professor
             */
            review_count: number;
        };
        /**
         * Review
         * @description Schema for review responses.
         */
        Review: {
            /**
             * Overall Rating
             * @description Overall rating (1-5)
             */
            overall_rating: number;
            /**
             * Difficulty Rating
             * @description Difficulty rating (1-5)
             */
            difficulty_rating: number;
            /**
             * Workload Rating
             * @description Workload rating (1-5)
             */
            workload_rating: number;
            /**
             * Comment
             * @description Review comment
             */
            comment?: string | null;
            /**
             * Semester
             * @description Semester (e.g., 'AY2024/25 Sem 1')
             */
            semester: string;
            /**
             * Year
             * @description Year
             */
            year: number;
            /**
             * Course Code
             * @description Course code (e.g., 'CS5224')
             */
            course_code: string;
            /**
             * University
             * @description University name (e.g., 'NUS')
             */
            university: string;
            /**
             * Professor Name
             * @description Professor name
             */
            professor_name?: string | null;
            /** Id */
            id: number;
            /**
             * User Id
             * @description User ID (Cognito sub)
             */
            user_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ReviewCreate
         * @description Schema for creating a review.
         */
        ReviewCreate: {
            /**
             * Overall Rating
             * @description Overall rating (1-5)
             */
            overall_rating: number;
            /**
             * Difficulty Rating
             * @description Difficulty rating (1-5)
             */
            difficulty_rating: number;
            /**
             * Workload Rating
             * @description Workload rating (1-5)
             */
            workload_rating: number;
            /**
             * Comment
             * @description Review comment
             */
            comment?: string | null;
            /**
             * Semester
             * @description Semester (e.g., 'AY2024/25 Sem 1')
             */
            semester: string;
            /**
             * Year
             * @description Year
             */
            year: number;
            /**
             * Course Code
             * @description Course code (e.g., 'CS5224')
             */
            course_code: string;
            /**
             * University Name
             * @description University name (e.g., 'NUS')
             */
            university_name: string;
            /**
             * Professor Name
             * @description Professor name
             */
            professor_name?: string | null;
            /**
             * Course Name
             * @description Course name (e.g., 'Cloud Computing')
             */
            course_name?: string | null;
        };
        /**
         * ReviewUpdate
         * @description Schema for updating a review.
         */
        ReviewUpdate: {
            /** Overall Rating */
            overall_rating?: number | null;
            /** Difficulty Rating */
            difficulty_rating?: number | null;
            /** Workload Rating */
            workload_rating?: number | null;
            /** Comment */
            comment?: string | null;
            /** Semester */
            semester?: string | null;
            /** Year */
            year?: number | null;
            /** Professor Name */
            professor_name?: string | null;
        };
        /**
         * University
         * @description University response schema.
         */
        University: {
            /**
             * Name
             * @description University name
             */
            name: string;
            /**
             * Id
             * @description University ID
             */
            id: number;
            /**
             * Review Count
             * @description Number of reviews for this university
             */
            review_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_detailed_health_detailed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_reviews_api_v1_reviews__get: {
        parameters: {
            query?: {
                /** @description Filter by professor name */
                professor_name?: string | null;
                /** @description Filter by course code */
                course_code?: string | null;
                /** @description Filter by university */
                university?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_api_v1_reviews__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_reviews_api_v1_reviews_me_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_stats_api_v1_reviews_stats_get: {
        parameters: {
            query?: {
                /** @description Filter by professor name */
                professor_name?: string | null;
                /** @description Filter by course code */
                course_code?: string | null;
                /** @description Filter by university */
                university?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_api_v1_reviews__review_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Review ID */
                review_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_review_api_v1_reviews__review_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Review ID */
                review_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_review_api_v1_reviews__review_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Review ID */
                review_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_professors_api_v1_professors__get: {
        parameters: {
            query?: {
                /** @description Filter by professor name (case-insensitive partial match) */
                name?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Professor"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_professor_api_v1_professors__professor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Professor ID */
                professor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Professor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_professor_reviews_api_v1_professors__professor_id__reviews_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Professor ID */
                professor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_professor_stats_api_v1_professors__professor_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Professor ID */
                professor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_api_v1_courses__get: {
        parameters: {
            query?: {
                /** @description Filter by course code (case-insensitive partial match) */
                code?: string | null;
                /** @description Filter by university (case-insensitive exact match) */
                university?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_api_v1_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Course ID */
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_reviews_api_v1_courses__course_id__reviews_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Course ID */
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_stats_api_v1_courses__course_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Course ID */
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_professors_api_v1_courses__course_id__professors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Course ID */
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_universities_api_v1_universities__get: {
        parameters: {
            query?: {
                /** @description Filter by university name (case-insensitive partial match) */
                name?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["University"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_professors_api_v1_search_professors_get: {
        parameters: {
            query: {
                /** @description Search query for professor name */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_courses_api_v1_search_courses_get: {
        parameters: {
            query: {
                /** @description Search query for course code */
                q: string;
                /** @description Whether to use exact match (default: true) */
                exact?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    global_search_api_v1_search_global_get: {
        parameters: {
            query: {
                /** @description Global search query */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_stats_api_v1_search_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
