"""Initial schema

Revision ID: 6080b1fc46c1
Revises: 
Create Date: 2025-11-10 23:52:12.258823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6080b1fc46c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('overall_rating', sa.Float(), nullable=False),
    sa.Column('difficulty_rating', sa.Float(), nullable=False),
    sa.Column('workload_rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('university_name', sa.String(length=255), nullable=False),
    sa.Column('professor_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_course_year', 'reviews', ['course_code', 'year'], unique=False)
    op.create_index('idx_review_created_at_desc', 'reviews', ['created_at'], unique=False)
    op.create_index('idx_review_university_course', 'reviews', ['university_name', 'course_code'], unique=False)
    op.create_index('idx_review_university_professor', 'reviews', ['university_name', 'professor_name'], unique=False)
    op.create_index('idx_review_user_created', 'reviews', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reviews_course_code'), 'reviews', ['course_code'], unique=False)
    op.create_index(op.f('ix_reviews_professor_name'), 'reviews', ['professor_name'], unique=False)
    op.create_index(op.f('ix_reviews_semester'), 'reviews', ['semester'], unique=False)
    op.create_index(op.f('ix_reviews_university_name'), 'reviews', ['university_name'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_year'), 'reviews', ['year'], unique=False)
    op.create_table('universities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_course_university_code', 'courses', ['university_id', 'code'], unique=False)
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    op.create_index(op.f('ix_courses_university'), 'courses', ['university'], unique=False)
    op.create_index(op.f('ix_courses_university_id'), 'courses', ['university_id'], unique=False)
    op.create_table('professors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professors_name'), 'professors', ['name'], unique=False)
    op.create_index(op.f('ix_professors_university_id'), 'professors', ['university_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professors_university_id'), table_name='professors')
    op.drop_index(op.f('ix_professors_name'), table_name='professors')
    op.drop_table('professors')
    op.drop_index(op.f('ix_courses_university_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_university'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_index('idx_course_university_code', table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_reviews_year'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_university_name'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_semester'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_professor_name'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_course_code'), table_name='reviews')
    op.drop_index('idx_review_user_created', table_name='reviews')
    op.drop_index('idx_review_university_professor', table_name='reviews')
    op.drop_index('idx_review_university_course', table_name='reviews')
    op.drop_index('idx_review_created_at_desc', table_name='reviews')
    op.drop_index('idx_review_course_year', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
