"""Add course_name to reviews table

Revision ID: 9a573e065c32
Revises: 6080b1fc46c1
Create Date: 2025-11-14 23:08:56.546315

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a573e065c32'
down_revision: str | Sequence[str] | None = '6080b1fc46c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable first
    op.add_column('reviews', sa.Column('course_name', sa.String(length=255), nullable=True))

    # Step 2: Populate existing rows with course_code as fallback
    op.execute("UPDATE reviews SET course_name = course_code WHERE course_name IS NULL")

    # Step 3: Make column NOT NULL now that all rows have values
    op.alter_column('reviews', 'course_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'course_name')
    # ### end Alembic commands ###
